### ISSUE TITLE
Unchecking "Import Inventory" Causes Inventory To Be Wiped #26

### ISSUE THREAD

**Issue by nrllewellyn** [zarmstrong/foundry-pathbuilder2e-import#2]
(Issues are disabled on the @zarmstrong fork, so hopefully this is the correct place to post issues!)

If you uncheck the "Import Equipment?" box during the import process, the character's inventory is cleared. (Expected behavior is that existing items would be left untouched.)

Tested with:
Foundry: 0.8.8
Pathbuilder 2e Importer: 0.6.2

**Comment by nrllewellyn** [comment]
Responding to comment on the original ticket: It's a bummer that this is difficult to implement--my players tend to track their build in PathBuilder and their inventory in Foundry.  (Just because it's easier that way.) But disabling it is definitely better than having a dangerous checkbox. :-)

**Comment by zarmstrong** [comment]
Release 0.6.4 removes the option to preserve inventory (since it wasn't working anyway).  This feature will be added back in the future.  

I had to remove the ability to preserve, as things were breaking across multiple imports to the same PC, so this feature needs to be rewritten from scratch and modernized to some of the latest features of the PF2e system.

**Comment by zarmstrong** [comment]
fixed a while ago
